name: dask

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'dask_ml/**'
      - '.github/workflows/dask.yml'

jobs:
  examples:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    # if: github.repository == 'optuna/optuna-examples'
    steps:
    - uses: actions/checkout@v2
    - name: setup-python${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install (Python)
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        pip install git+https://github.com/optuna/optuna.git
        python -c 'import optuna'

        pip install -r dask_ml/requirements.txt
    - name: Run examples
      run: |
        python dask_ml/dask_ml_simple.py
      env:
        OMP_NUM_THREADS: 1
