name: pytorch

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'pytorch/**'
      - '.github/workflows/pytorch.yml'

jobs:
  examples:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    # if: github.repository == 'optuna/optuna-examples'
    steps:
    - uses: actions/checkout@v2
    - name: setup-python${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install (apt)
      run: |
        sudo apt-get update
        sudo apt-get -y install openmpi-bin libopenmpi-dev
    - name: Install (Python)
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        pip install git+https://github.com/optuna/optuna.git
        python -c 'import optuna'

        pip install -r pytorch/requirements.txt
    # - name: Run PyTorch examples
    #   run: |
    #     python pytorch/pytorch_simple.py
    #   env:
    #     OMP_NUM_THREADS: 1
    - name: Run PyTorch checkpoint example
      run: |
        timeout 20 python pytorch/pytorch_checkpoint.py > /dev/null
        python pytorch/pytorch_checkpoint.py > /dev/null
      env:
        OMP_NUM_THREADS: 1
    # - name: Run multi-node examples
    #   run: |
    #     STORAGE_URL=sqlite:///example.db
    #     mpirun -n 2 -- python pytorch/pytorch_distributed_simple.py
    #   env:
    #     OMP_NUM_THREADS: 1
    # - name: Run PyTorch Ignite examples
    #   run: |
    #     python pytorch/pytorch_ignite_simple.py
    #   env:
    #     OMP_NUM_THREADS: 1
    # - name: Run PyTorch Lightning examples
    #   run: |
    #     python pytorch/pytorch_lightning_simple.py
    #   env:
    #     OMP_NUM_THREADS: 1
